### PR TITLE
remove engines

### PR DESCRIPTION
**Pull request by kirovilya**
Can you remove the dependency on the version of nodejs?
Because engineStrict does not work with npm > 3.0.0

### CODE REVIEW

**Comment by SeanSobey** [comment]
Hi

Since the recent update to the canvas dependency more versions of node are supported.
I added the `engines` field to help warn/protect against unsupported versions of node, where this library will not work. I have updated the [config](https://github.com/SeanSobey/ChartjsNodeCanvas/blob/master/package.json) and build pipeline to support and test with supported and active versions of node but am hesitant to remove it as new versions of node require adding support from canvas and may not work straight away.

Does this update work for your use case? I am not 100% sure what you mean by:
> Because engineStrict does not work with npm > 3.0.0
As far as I understand npm < 3.0.0 did not support `engineStrict` and effectively assumed `engineStrict: true`. If so then my update should be relevant.

Thanks for raising this issue

**Comment by kirovilya** [comment]
Hey. I tried using your package with NodeJS 8 and it works for me, because the main dependency is **canvas**, where the required version of NodeJS> = 6 is https://github.com/Automattic/node-canvas/blob/master/package.json#L65
Therefore, even if you remove the dependencies from your package, it will not be able to install on NodeJS below 6 (due to dependencies in canvas)

**Comment by kirovilya** [comment]
About engineStrict - https://github.com/npm/cli/blob/latest/changelogs/CHANGELOG-3.md#enginestrict

**Comment by SeanSobey** [comment]
Thanks for the links, I did not see those before.

All the issues we have had with node versions have been forward compatibility. But for now, I am happy to be optimistic that `canvas` has addressed the `node-gyp` issues via prebuilt binaries  and will remove the version clamp here, thanks!

**Pull request merged**
