### PR TITLE
Add a synchronous renderToDataURL function

### PR DESCRIPTION
**Pull request by BryceBarbara**
Although the canvas supports returning the result synchronously, this library lacked a way to use that functionality. This PR adds it.

### CODE REVIEW

**Comment by SeanSobey** [comment]
Hi, thanks for your contribution!

I did not expect this to be a common use-case, since it will be a blocking call, but do not mind adding it to this library.

[toBuffer](https://github.com/Automattic/node-canvas#canvastobuffer) also has a sync version which might be worthwhile adding for completion. Also, no tests added to cover the method? I don't mind adding these myself in a separate PR.

**Comment by BryceBarbara** [comment]
I didn't have a ton of time unfortunately to put into this one so it's pretty bare bones. I don't know when I'd get enough free time to create the tests, I apologize. And true, it being a blocking call usually isn't ideal however (if I understand this correctly) it's a purely computational operation. It's not waiting on file/network IO or anything so I'm curious why it's async to begin with.

My personal use-case is in a custom MJML component where it's already blocking to convert the MJML to HTML so introducing async logic in the pipeline isn't ideal and isn't supported.

**Comment by SeanSobey** [comment]
The Chart JS logic will indeed happen in the js runtime but the [canvas implementation](https://github.com/Automattic/node-canvas) is implemented as a native module in C++, using [Cairo](http://cairographics.org/), and uses a [non-blocking](https://github.com/Automattic/node-canvas/blob/master/src/Canvas.cc#L226) [libuv](http://libuv.org/) implementation.

In practise his means that when this lib calls [`canvas.toBuffer`](https://github.com/SeanSobey/ChartjsNodeCanvas/blob/master/src/index.ts#L75) for example, when called using the async API then the js runtime can execute other code while the canvas image/buffer/stream is rendering on a different thread. Also, multiple chart configs could potentially be rendering concurrently which is what this lib tries to take advantage of in the API design.

Canvas rendering could potentially be quite intensive, for larger images, [rasterization](https://en.wikipedia.org/wiki/Raster_image_processor) etc, and NodeJS is designed to leverage [non-blocking](https://nodejs.org/de/docs/guides/blocking-vs-non-blocking/) JS.

However I have no objection adding the sync APIs to this library and have done so (version 2.3.0) with the tests and docs included. The tests picked up an error on this PR (`chart.destory();` not `chart.destroy();`)

**Comment by BryceBarbara** [comment]
That's perfect! I appreciate the fast and detailed responses! I caught the destroy typo in my own codebase after running it, I'm embarrassed I didn't think to update it in this one. 😅

Thanks for the info and the links! I've added them to my list of things to dive deeper into.

**Pull request closed without merging**
